spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    mail:
        host: ${SPRING_MAIL_HOST}
        port: ${SPRING_MAIL_PORT:587} # MailDev SMTP port 1080 for web interface
        username: ${SPRING_MAIL_USERNAME}
        password: ${SPRING_MAIL_PASSWORD:xsmtpsib-3b69cda5254233696b0810e9e2b782e05ca27187c6f0d5d307358486f517388b-Ufg7YdtEka1Zs0J5}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                connectiontimeout: 5000
                timeout: 3000
                writetimeout: 5000

application:
    security:
        jwt:
            secret-key: ${JWT_SECRET_KEY}
            expiration: ${JWT_EXPIRATION_TIME}
            header: Authorization
            prefix: Bearer
    
    mailing:
        frontend:
            activation-url: http://localhost:8080/activate-account # Frontend change frontend url


server:
    port: 8088
