spring:
    profiles:
        active: dev
    application:
        name: user-auth-service
    servlet:
        multipart:
            max-file-size:
                50MB
    # config:
    #     import: "configserver:"
    # cloud:
    #     config:
    #         uri: http://localhost:8888


springdoc:
    default-produces-media-type: application/json

server:
    servlet:
        context-path: /api/v1