spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/userAuth
        username: username
        password: passwd
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    mail:
        host: localhost
        port: 1025 # MailDev SMTP port 1080 for web interface
        username: getmyuri
        password: passwd
        properties:
            mail:
                smtp:
                    trust:"*"
                auth: true
                starttls:
                    enable: true
                connectiontimeout: 5000
                timeout: 3000
                writetimeout: 5000

application:
    security:
        jwt:
            secret: mySecretKey
            expiration: 3600 # 1 hour in seconds
            header: Authorization
            prefix: Bearer