spring:
    profiles:
        active: dev
    application:
        name: user-auth-service
    servlet:
        multipart:
            max-file-size:
                50MB
    # config:
    #     import: "configserver:"
    # cloud:
    #     config:
    #         uri: http://localhost:8888


springdoc:
    default-produces-media-type: application/json

server:
    servlet:
        context-path: /api/v1

application:
  security:
    jwt:
      # secret-key, expiration are typically loaded from config server or environment variables in a real setup
      # For local development, they can be defined here if not overridden.
      # secret-key: your-very-secure-secret-key-for-jwt # Example: replace or load from env
      # expiration: 86400000 # 24 hours in milliseconds for access token, example
firebase:
  project:
    id: "${FIREBASE_PROJECT_ID}"
  private:
    key: "${FIREBASE_PRIVATE_KEY}"
  client:
    email: "${FIREBASE_CLIENT_EMAIL}"